import type { Metadata } from "next";
import { Karla } from "next/font/google";
import { Toaster } from "sonner";
import Script from "next/script";
import { ThemeProvider } from "@/app/components/theme-provider";
import "./globals.css";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aleet - Driver Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${karla.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        {/* Prevent flash of wrong theme */}
        <Script
          id="theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='dark'){document.documentElement.classList.add('dark')}else{document.documentElement.classList.remove('dark')}}catch(e){}})()`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#0d1a19",
                border: "1px solid #1e2b2a",
                color: "#e8e8e8",
                fontFamily: "var(--font-karla), Karla, sans-serif",
                fontSize: "14px",
                borderRadius: "12px",
                boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
              },
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

